FROM archlinux:latest
RUN pacman -Syyu --noconfirm && pacman -S --noconfirm git openssh sudo
ARG USERNAME="archie"
ARG INSTALL_NODE="false"
ARG INSTALL_ZSH="true"

# Install node if needed
RUN if [ "$INSTALL_NODE" = "true" ]; then pacman -S --noconfirm nodejs; fi

# Create wheel group and add it to the sudoers file
RUN echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Add the user, give it a home directory and add it to the wheel group
RUN useradd -m -s /bin/bash -G wheel $USERNAME

# Add my dotfiles repo to $USERNAME's home directory
ADD --chown=$USERNAME "https://github.com/VictorGamerLOL/dotfiles" /home/$USERNAME

# Add zsh if needed
RUN if [ "$INSTALL_ZSH" = "true" ]; then pacman -S --noconfirm zsh; fi